In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [2]:
square=np.zeros((10,10),np.uint8)
cv2.rectangle(square,(2,2),(6,6),(2,1))
print(square-9)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 2 2 2 2 2 0 0 0]
 [0 0 2 0 0 0 2 0 0 0]
 [0 0 2 0 0 0 2 0 0 0]
 [0 0 2 0 0 0 2 0 0 0]
 [0 0 2 2 2 2 2 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [4]:
circle=np.zeros((10,10),np.uint8)
cv2.rectangle(square,(5,5),4,3,-1)
print(circle)

error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'rectangle'
> Overload resolution failed:
>  - Can't parse 'pt2'. Input argument doesn't provide sequence protocol
>  - Can't parse 'rec'. Expected sequence length 4, got 2
>  - Can't parse 'pt2'. Input argument doesn't provide sequence protocol
>  - Can't parse 'rec'. Expected sequence length 4, got 2
